name: codex2api-sqlite-local

services:
  codex2api:
    build: .
    container_name: codex2api-sqlite-local
    ports:
      - "${CODEX_PORT:-8080}:${CODEX_PORT:-8080}"
    env_file:
      - .env
    volumes:
      - sqlite-data-local:/data
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - resin_net

volumes:
  sqlite-data-local:
    name: codex2api-sqlite-local_sqlite-data-local

networks:
  resin_net:
    external: true